package com.cydercode.jtube.error;

public enum ErrorResult {
  VIDEO_UNAVAILABLE,
  PRIVATE_VIDEO,
  REMOVED_VIOLATION,
  LIVESTREAM_UNAVAILABLE,
  ONLY18PLUS,
  JTUBE_ERROR,
  STILL_PROCESSING,
  INCOMPLETE_ID,

  HTTP_404,
  UNKNOWN
}
